[package]
name = "headless_webview"
version = "0.1.0"
edition = "2021"

[dependencies]
url = "2.2"
thiserror = "1.0.30"
http = "0.2.6"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"

[features]
default = []
protocol = []